gitlab-extracter no longer export content to csv file

diff --git a/gitlab-extracter b/gitlab-extracter
--- a/gitlab-extracter
+++ b/gitlab-extracter
@@ -9,6 +9,7 @@ URL=https://gitlab.com
 NO_PROXY=false
 CSV_FILE=
 BROWSE_FILE=
+VERBOSE=false
 PARAMS="?per_page=100&page=1"
 DESCRIPTION="Retrieve gitlab project's content as JSON file. \n \
              	The content is either stored in a file or printed on standard output. \n \
@@ -16,7 +17,7 @@ DESCRIPTION="Retrieve gitlab project's content as JSON file. \n \
              	\n \
              	NOTE : 'curl' package has to be installed."
 GITLAB_API=api/v4/projects
-USAGE="Usage: ${0} --id PROJECT_ID [-h|--help] [-a|--auth KEY] [-b|--browse] [-o|--output OUTPUT.json] [-u|--url URL] [--no-proxy] [--export-csv CSV_FILE.csv]\n \
+USAGE="Usage: ${0} --id PROJECT_ID [-h|--help] [-a|--auth KEY] [-b|--browse] [-o|--output OUTPUT.json] [-u|--url URL] [--no-proxy]\n \
 \t\t-h|--help                       : Print this help.\n \
 \t\t-a|--auth                       : Authentication key \n \
 \t\t-b|--browse                     : Open JSON content with default web browser. \n \
@@ -24,24 +25,27 @@ USAGE="Usage: ${0} --id PROJECT_ID [-h|--help] [-a|--auth KEY] [-b|--browse] [-o
 \t\t-o|--output                     : Save JSON content into given file. \n \
 \t\t-u|--url                        : Gitlab server URL ('${URL}' as default value).\n \
 \t\t--no-proxy                      : Don't use proxies, even if the appropriate *_proxy environment variable is defined.\n \
-\t\t--export-csv                    : Convert JSON to CSV file which includes main fields.\n \
 \n"
 
-DEPENDENCIES="curl jq"
+DEPENDENCIES="curl"
+
+log()
+{
+	echo -e "$*" >&2
+}
 
 fail()
 {
-	echo "ERROR: $*" >&2
+	log "ERROR: $*"
 	exit 1
 }
 
 step()
 {
 	len=$(echo "$*" | awk '{print length}')
-	echo
-	seq -s'#' 0 ${len} | tr -d '[:digit:]'
-	echo "$*"
-	seq -s'#' 0 ${len} | tr -d '[:digit:]'
+	log "$(seq -s'#' 0 ${len} | tr -d '[:digit:]')"
+	log "$*"
+	log "$(seq -s'#' 0 ${len} | tr -d '[:digit:]')"
 }
 
 #######################
@@ -57,17 +61,23 @@ while [ ${#} -ne 0 ]; do
 		-i|--id)                    shift; ID=${1};;
 		-o|--output)                shift; OUTPUT=${1};;
 		-u|--url)                   shift; URL=${1};;
+		-v|--verbose)               VERBOSE=true;;
 		--no-proxy)                 NO_PROXY=true;;
-		--export-csv)               shift; CSV_FILE=${1};;
 		*)                          printf "${USAGE}"; exit 1;;
 	esac
 	shift
 done
 
 [ -z "${ID}" ] && fail "You shall specify gitlab project id."
-[ -z "${KEY}" ] || AUTH="?private_token=${KEY}"
+[ -z "${KEY}" ] || AUTH="&private_token=${KEY}"
 
-${NO_PROXY} && { echo "Proxies are disabled"; unset {http,https,HTTP,HTTPS}_{proxy,PROXY}; }
+${NO_PROXY} && { log "Proxies are disabled"; unset {http,https,HTTP,HTTPS}_{proxy,PROXY}; }
+
+[ -z "${OUTPUT}" ] ||
+{
+	[[ "${OUTPUT}" =~ ^.+\.json$ ]] || OUTPUT=${OUTPUT}.json
+	exec > ${OUTPUT}
+}
 
 ##########################
 ### Check dependencies ###
@@ -75,21 +85,22 @@ ${NO_PROXY} && { echo "Proxies are disabled"; unset {http,https,HTTP,HTTPS}_{pro
 step "### Check dependencies ###"
 dpkg -s ${DEPENDENCIES} > /dev/null 2>&1 ||
 {
-	echo "Missing following packages :"
-	echo -n "    "
+	log "Missing following packages :"
+	log -n "    "
 	for dep in ${DEPENDENCIES}; do
-		dpkg -s "${dep}" > /dev/null 2>&1 || echo -n "${dep} "
+		dpkg -s "${dep}" > /dev/null 2>&1 || log -n "${dep} "
 	done
-	echo
-	echo "Install them running 'apt-get install' and retry"
+	log
+	log "Install them running 'apt-get install' and retry"
 	exit 1
 }
+log "OK"
 
 ###################################
 ### Check that URL is reachable ###
 ###################################
 step "### Check that ${URL} is reachable ###"
-ping -c1 -W1 $(sed 's:^.*\://\(.*$\):\1:' <<< ${URL}) > /dev/null 2>&1 && echo "OK" || fail "Error : ${URL} is not reachable"
+ping -c1 -W1 $(sed 's:^.*\://\(.*$\):\1:' <<< ${URL}) > /dev/null 2>&1 && log "OK" || fail "Error : ${URL} is not reachable"
 
 ########################
 ### Retrieve content ###
@@ -101,7 +112,7 @@ HEADER_FILE=$(mktemp /tmp/gitlab-extracter.XXXXXX.header)
 page_num=1
 while [ ! -z "${page_num}" ]
 do
-
+	log "."
 	http_params="?per_page=100&page=${page_num}${AUTH}"
 	curl -s -D ${HEADER_FILE} ${URL}/${GITLAB_API}/${ID}/issues${http_params} >> ${CONTENT_FILE}
 	http_return_code=$(head -n 1 ${HEADER_FILE} | awk '{print $2}')
@@ -114,53 +125,19 @@ done
 page_total=$(grep X-Total-Pages: ${HEADER_FILE} | grep -oE '[0-9]+')
 entry_num=$(grep X-Total: ${HEADER_FILE} | grep -oE '[0-9]+')
 
-echo "Retrieved ${entry_num} entries on ${page_total} pages"
-
-######################
-### Save JSON file ###
-######################
-[ -z "${OUTPUT}" ] || {
-	[[ "${OUTPUT}" =~ ^.+\.json$ ]] || OUTPUT=${OUTPUT}.json
-	step "### Saving JSON to ${OUTPUT} ###"
-
-	cp ${CONTENT_FILE} ${OUTPUT} && echo "OK" || echo "Error : Unable to save file to ${OUTPUT}"
-}
-
-#######################
-### Export CSV file ###
-#######################
-[ -z "${CSV_FILE}" ] || {
-	[[ "${CSV_FILE}" =~ ^.+\.csv$ ]] || OUTPUT=${CSV_FILE}.csv
-	step " ### Export CSV file to ${CSV_FILE} ###"
-
-	sed -i 's/\\"/@@QUOTES@@/g' ${CONTENT_FILE}
-
-	CSV_SEPARATOR=';'
-
-	echo "Numéro${CSV_SEPARATOR}Titre${CSV_SEPARATOR}Statut${CSV_SEPARATOR}Milestone${CSV_SEPARATOR}Labels${CSV_SEPARATOR}Assignée${CSV_SEPARATOR}Auteur${CSV_SEPARATOR}Date création${CSV_SEPARATOR}Description" > ${CSV_FILE}
-
-	# JSON filters can be implemented here as follow :
-	#     | select(.labels | index(\"Mantis\") | not) ==> Remove all elements containing "Mantis" into 'labels' list
-	#     | select(.labels | index(\"Bug\"))          ==> Keep only elements containing "Bug" into 'labels' list
-
-	jq -r ".[]
-	      | select(.labels | index(\"Mantis\") | not)
-	      | select(.labels | index(\"Interne\") | not)
-	      | select(.labels | index(\"Récit Utilisateur\") | not)
-	      | select(.labels | index(\"À valider\") | not)
-	      | select(.labels | index(\"À surveiller\") | not)
-	      | select(.labels | index(\"Bug\"))
-	      | \"\(.iid)${CSV_SEPARATOR}\(.title)${CSV_SEPARATOR}\(.state)${CSV_SEPARATOR}\(.milestone.title)${CSV_SEPARATOR}\(.labels)${CSV_SEPARATOR}\(.assignee.name)${CSV_SEPARATOR}\(.author.name)${CSV_SEPARATOR}\(.created_at)${CSV_SEPARATOR}\\\"\(.description)\\\"\"" ${CONTENT_FILE} >> ${CSV_FILE} && echo "OK" || echo "Error : Unable to convert output to CSV file"
-
-	sed -i 's/@@QUOTES@@/\\""/g' ${CSV_FILE}
-}
+log "Retrieved ${entry_num} entries on ${page_total} pages"
 
 #####################
 ### Print content ###
 #####################
-[ -z "${OUTPUT}" ] && BROWSE_FILE=${CONTENT_FILE} || BROWSE_FILE=${OUTPUT}
-${BROWSE} && { sensible-browser ${BROWSE_FILE} || fail "Error : Unable to open file with default web browser"; } || [ -z "${OUTPUT}" ] && cat ${BROWSE_FILE}
-echo
+step "### JSON content ###"
+[ -z "${OUTPUT}" ] || log "Content saved to '${OUTPUT}'"
+cat ${CONTENT_FILE}
+
+######################
+### Browse content ###
+######################
+${BROWSE} && { sensible-browser ${CONTENT_FILE} || fail "Error : Unable to open file with default web browser"; }
 
 exit 0
 
