Implement progress bar while retriving issues

diff --git a/gitlab-extracter b/gitlab-extracter
--- a/gitlab-extracter
+++ b/gitlab-extracter
@@ -110,7 +110,7 @@ log "OK"
 ### Check that URL is reachable ###
 ###################################
 step "### Check that ${URL} is reachable ###"
-ping -c1 -W1 $(sed 's:^.*\://\(.*$\):\1:' <<< ${URL}) > /dev/null 2>&1 && log "OK" || fail "Error : ${URL} is not reachable"
+ping -c1 -W 5 $(sed 's:^.*\://\(.*$\):\1:' <<< ${URL}) > /dev/null 2>&1 && log "OK" || fail "Error : ${URL} is not reachable"
 
 ########################
 ### Retrieve content ###
@@ -119,23 +119,36 @@ step "### Retrieve project's issues ###"
 CONTENT_FILE=$(mktemp /tmp/gitlab-extracter.XXXXXX.json)
 HEADER_FILE=$(mktemp /tmp/gitlab-extracter.XXXXXX.header)
 
-page_num=1
-while [ ! -z "${page_num}" ]
+http_params="?per_page=1&page=1${AUTH}"
+curl -s -D ${HEADER_FILE} ${URL}/${GITLAB_API}/${ID}/issues${http_params} >> /dev/null
+
+entry_num=$(grep X-Total: ${HEADER_FILE} | grep -oE '[0-9]+')
+
+log "Retrieving ${entry_num} entries"
+
+if [ "${entry_num}" -ge 100 ]; then
+	per_page=100
+else
+	per_page=1
+fi
+page=1
+
+while [ ! -z "${page}" ]
 do
-	log "."
-	http_params="?per_page=100&page=${page_num}${AUTH}"
+	http_params="?per_page=${per_page}&page=${page}${AUTH}"
 	curl -s -D ${HEADER_FILE} ${URL}/${GITLAB_API}/${ID}/issues${http_params} >> ${CONTENT_FILE}
 	http_return_code=$(head -n 1 ${HEADER_FILE} | awk '{print $2}')
 	grep -E '2[0-9]{2}' > /dev/null <<< ${http_return_code} || { cat ${HEADER_FILE}; fail "Error : Server returned HTTP status code ${http_return_code}"; }
 
-	page_num=$(grep X-Next-Page: ${HEADER_FILE} | grep -oE '[0-9]+')
+	percent=$((100*${page}*${per_page}/${entry_num}))
+	echo -ne "[$(seq -s'#' 0 ${percent} | tr -d '[:digit:]')$(seq -s'.' 0 $((100-${percent})) | tr -d '[:digit:]')](${percent}%)\r" >&2
 
+	page=$(grep X-Next-Page: ${HEADER_FILE} | grep -oE '[0-9]+')
 done
 
-page_total=$(grep X-Total-Pages: ${HEADER_FILE} | grep -oE '[0-9]+')
-entry_num=$(grep X-Total: ${HEADER_FILE} | grep -oE '[0-9]+')
+echo >&2
 
-log "Retrieved ${entry_num} entries on ${page_total} pages"
+log "OK"
 
 #####################
 ### Print content ###
